### ISSUE TITLE
Link to getonboard site doesn't work.

### ISSUE THREAD

**Issue by seba-zuniga** [mathiasd88/Getonbrd-Daily-Search#2]
Can you check why the extension doesn't redirect to getOnBoard Site well? After clik on an advice, show this...
Thanks...

![screenshot_4](https://user-images.githubusercontent.com/9038785/27596068-704f1c0e-5b2c-11e7-8541-4b0b54977d4c.png)

**Comment by mathiasdonoso** [comment]
Fix in https://github.com/mathiasd88/Getonbrd-Daily-Search/tree/mathiasd88/topic-2-link-does-not-work.

Branch was already merged.
